# Generated by Django 5.0.4 on 2024-06-15 13:28

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_usuarios_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotos_locales',
            name='imagen',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=50, scale=None, size=[1920, 1080], upload_to='fotos_locales/'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=50, scale=None, size=[1920, 1080], upload_to='productos_imagenes/'),
        ),
    ]
